sonar.projectKey=flutter-fsd-app
sonar.projectName=Flutter FSD App
sonar.sources=lib
sonar.tests=test
sonar.language=dart
sonar.sourceEncoding=UTF-8

# EXCLUSIONES (Importante para FSD)
sonar.exclusions=android/**, ios/**, web/**, **/*.g.dart, **/*.freezed.dart, lib/generated/**

# ESTA ES LA LÍNEA CLAVE:
# Le decimos al scanner: "No analices, solo lee este archivo que ya generé"
sonar.dart.analysis.reportPath=dart_analysis.txt